-- 008_about_contact.sql — Secciones Nosotros y Contacto (con mapa)
CREATE TABLE IF NOT EXISTS cms_about (
  id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  provider_id INT UNSIGNED NULL DEFAULT NULL,
  title VARCHAR(150) NOT NULL DEFAULT 'Nosotros',
  subtitle VARCHAR(255) NOT NULL DEFAULT '',
  content TEXT NOT NULL,
  image VARCHAR(1000) NOT NULL DEFAULT '',
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_about_provider (provider_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS cms_contact (
  id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  provider_id INT UNSIGNED NULL DEFAULT NULL,
  title VARCHAR(150) NOT NULL DEFAULT 'Contacto',
  subtitle VARCHAR(255) NOT NULL DEFAULT '',
  address VARCHAR(255) NOT NULL DEFAULT '',
  phone VARCHAR(50) NOT NULL DEFAULT '',
  email VARCHAR(150) NOT NULL DEFAULT '',
  whatsapp VARCHAR(50) NOT NULL DEFAULT '',
  hours VARCHAR(255) NOT NULL DEFAULT '',
  lat DECIMAL(10,7) NULL DEFAULT NULL,
  lng DECIMAL(10,7) NULL DEFAULT NULL,
  map_url VARCHAR(1000) NOT NULL DEFAULT '',
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_contact_provider (provider_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
